version: "3.8"

services:
  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "4004:4004"
    networks:
      - patient-net

networks:
  patient-net:
    external: true