version: '3.8'

services:
  analytics-service:
    build: .
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"   # Expose container port 4002 as host port 9002
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - patient-net

networks:
  patient-net:
    external: true
