apiVersion: apps/v1
kind: Deployment

metadata:
  name: patient-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: patient-service

  template:
    metadata:
      labels:
        app: patient-service

    spec:
      containers:
        - name: patient-service

          image: arpit420/patient-service:v1

          ports:
            - containerPort: 4000

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/patientdb

            - name: SPRING_DATASOURCE_USERNAME
              value: patientuser

            - name: SPRING_DATASOURCE_PASSWORD
              value: patientpass

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092