version: "3.8"

services:
  patient-service:
    build: .
    container_name: patient-service
    restart: always

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patientdb
      SPRING_DATASOURCE_USERNAME: patientuser
      SPRING_DATASOURCE_PASSWORD: patientpass

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    ports:
#      - "4000:4000"

#    depends_on:
#      - mysql

    networks:
      - patient-net

networks:
  patient-net:
    external: true